# Generated by Django 5.1.7 on 2025-04-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
