# Generated by Django 5.1.7 on 2025-07-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_connection_connection_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connection",
            old_name="connection_id",
            new_name="connectionId",
        ),
    ]
