# Generated by Django 5.1.7 on 2025-04-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_category_parent_alter_auctionimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
    ]
