# Generated by Django 5.1.7 on 2025-04-09 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_message_options_alter_message_connection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['-updated'], 'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterField(
            model_name='connection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('sender', 'receiver')},
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['sender', 'receiver'], name='api_connect_sender__e04639_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['updated'], name='api_connect_updated_8047c2_idx'),
        ),
    ]
