# Generated by Django 5.1.7 on 2025-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_connection_options_alter_connection_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest_location',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
