# Generated by Django 5.1.7 on 2025-04-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_latest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_price',
        ),
    ]
