# Generated by Django 5.1.7 on 2025-06-23 17:09

import api.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=api.users.utils.generate_unique_username, max_length=35, null=True, unique=True),
        ),
    ]
