# Generated by Django 5.1.7 on 2025-07-03 02:03

import api.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_user_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="assets/default.png",
                null=True,
                upload_to=api.users.utils.upload_thumbnail,
            ),
        ),
    ]
