# Generated by Django 5.1.7 on 2025-07-06 15:26

import api.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_user_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="https://quicauct-mediafiles.s3.us-east-1.amazonaws.com/static/assets/default.png",
                null=True,
                upload_to=api.users.utils.upload_thumbnail,
            ),
        ),
    ]
