# Generated by Django 5.1.7 on 2025-07-03 04:12

import api.auctions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_user_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionimage",
            name="image",
            field=models.ImageField(
                default="assets/defaultAuct.jpg",
                upload_to=api.auctions.utils.upload_to_s3,
            ),
        ),
    ]
